import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "zen-ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" title="zen-ecommerce">
        <body>
          <main>
            <Header />
            {children}

          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
